<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/send" method="post">
    <div class="form-group">
        <label for="message">Message</label>
        <input type="text" class="form-control" name="message" id="message" placeholder="Enter message">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</body>
</html>
